package org.adk4s.record

import munit.FunSuite
import org.adk4s.record.canonical.CallKind
import org.adk4s.record.canonical.CanonicalBody
import org.adk4s.record.canonical.CanonicalForm

/**
 * Type-level contract tests for CallKey, RolloutId, CallKind, CanonicalForm.
 *
 * spec: add-adk4s-record/call-key — Requirement: RolloutId is a non-empty refined type
 * spec: add-adk4s-record/call-key — Requirement: CallKey is a stable digest
 * spec: add-adk4s-record/call-key — Requirement: CallKind discriminates call types
 * spec: add-adk4s-record/call-key — Requirement: Canonical form is inspectable
 */
class CallKeyTypeContract extends FunSuite:

  // ── Scenario: RolloutId rejects empty string at runtime ─────────────
  // spec: add-adk4s-record/call-key — Scenario: RolloutId rejects empty string
  test("RolloutId.refineEither rejects empty string"):
    val result = RolloutId.refineEither("")
    assert(result.isLeft, "Empty string should be rejected by RolloutId")

  // ── Scenario: RolloutId accepts non-empty string at runtime ─────────
  // spec: add-adk4s-record/call-key — Scenario: RolloutId accepts non-empty string
  test("RolloutId.refineEither accepts non-empty string"):
    val result = RolloutId.refineEither("run-1")
    assert(result.isRight, "Non-empty string should be accepted by RolloutId")

  // ── Scenario: CallKind has exactly three variants ───────────────────
  // spec: add-adk4s-record/call-key — Scenario: CallKind has three variants
  test("CallKind has exactly three variants: MODEL, TOOL, EMBEDDING"):
    val variants: List[CallKind] = List(CallKind.MODEL, CallKind.TOOL, CallKind.EMBEDDING)
    assertEquals(variants.length, 3)
    assertEquals(variants.toSet.size, 3, "All variants must be distinct")

  // ── Scenario: keyVersion is a positive integer ──────────────────────
  // spec: add-adk4s-record/call-key — Scenario: keyVersion is a positive integer
  test("keyVersion is a positive integer"):
    assert(keyVersion > 0, s"keyVersion must be positive, got $keyVersion")

  // ── Scenario: CanonicalForm carries keyVersion, kind, and body ──────
  // spec: add-adk4s-record/call-key — Scenario: Canonical form is inspectable
  test("CanonicalForm carries keyVersion, kind, and body"):
    val body = CanonicalBody.embedding(org.adk4s.record.canonical.EmbeddingBody("test", "model-1"))
    val form = CanonicalForm(keyVersion, CallKind.EMBEDDING, body)
    assertEquals(form.keyVersion, keyVersion)
    assertEquals(form.kind, CallKind.EMBEDDING)

  // ── Scenario: CallKey.fromDigest constructs a key ───────────────────
  // spec: add-adk4s-record/call-key — Scenario: CallKey is constructible from a digest
  test("CallKey.fromDigest constructs a key"):
    val key: CallKey = CallKey.fromDigest("abc123")
    assertEquals(key.value, "abc123")

  // ── Scenario: CallKey equality is by digest value ───────────────────
  // spec: add-adk4s-record/call-key — Scenario: CallKey equality is by digest
  test("CallKey equality is by digest value"):
    val k1: CallKey = CallKey.fromDigest("same")
    val k2: CallKey = CallKey.fromDigest("same")
    val k3: CallKey = CallKey.fromDigest("different")
    assert(k1 == k2, "Same digest should produce equal keys")
    assert(k1 != k3, "Different digests should produce unequal keys")

  // ── Scenario: Generated schema is available at compile time ─────────
  // spec: add-adk4s-record/call-key — Requirement: Canonical form is inspectable
  test("CanonicalForm schema is generated from Smithy IDL at compile time"):
    val s = CanonicalForm.schema
    assert(s != null, "Schema for CanonicalForm should be generated by smithy4s codegen")
    assertEquals(s.shapeId.name, "CanonicalForm")
    assertEquals(s.shapeId.namespace, "org.adk4s.record.canonical")
