package org.adk4s.structured.test

import cats.effect.IO
import fs2.Stream
import munit.CatsEffectSuite
import org.adk4s.structured.core.{ Prompt, Schema, StructuredLLM }
import org.llm4s.error.LLMError
import org.llm4s.llmconnect.LLMClient
import org.llm4s.llmconnect.model.AssistantMessage
import org.llm4s.llmconnect.model.Completion
import org.llm4s.llmconnect.model.CompletionOptions
import org.llm4s.llmconnect.model.Conversation
import org.llm4s.llmconnect.model.StreamedChunk
import org.llm4s.llmconnect.model.SystemMessage
import org.llm4s.llmconnect.model.UserMessage
import org.llm4s.types.Result

class StructuredLLMStreamingTest extends CatsEffectSuite:

  // Schema for Resume (Resume type already generated by smithy4s)
  given Schema[Resume] = Schema.instance(
    """structure Resume {
      |  @required
      |  name: String
      |  @required
      |  skills: StringList
      |  @required
      |  seniority: SeniorityLevel
      |  education: EducationList
      |}""".stripMargin
  )(using summon[smithy4s.schema.Schema[Resume]])

  test("streamWithResult emits tokens and parses final result") {
    // JSON response split into chunks for streaming
    val jsonChunks: List[String] = List(
      """{"name":""",
      """ "Jane """,
      """Doe", """,
      """"skills": """,
      """["Scala",""",
      """ "FP"],""",
      """ "senio""",
      """rity": """,
      """"SENIOR"}"""
    )

    val fullJson: String = jsonChunks.mkString

    // Mock LLM client that streams chunks
    val mockClient: LLMClient = new LLMClient:
      override def complete(
        conversation: Conversation,
        options: CompletionOptions
      ): Result[Completion] =
        val completion: Completion = Completion(
          id = "mock-id",
          created = 0L,
          content = fullJson,
          model = "mock-model",
          message = AssistantMessage(Some(fullJson)),
          toolCalls = List.empty,
          usage = None,
          thinking = None
        )
        Right(completion)

      override def streamComplete(
        conversation: Conversation,
        options: CompletionOptions,
        onChunk: StreamedChunk => Unit
      ): Result[Completion] =
        // Emit chunks via callback
        jsonChunks.foreach { chunkContent =>
          val chunk: StreamedChunk = StreamedChunk(
            id = "mock-chunk-id",
            content = Some(chunkContent),
            toolCall = None,
            finishReason = None,
            thinkingDelta = None
          )
          onChunk(chunk)
        }

        // Final chunk with finish reason
        onChunk(StreamedChunk(
          id = "mock-chunk-id",
          content = None,
          toolCall = None,
          finishReason = Some("stop"),
          thinkingDelta = None
        ))

        complete(conversation, options)

      override def getContextWindow(): Int = 8192
      override def getReserveCompletion(): Int = 512

    val structured: StructuredLLM[IO] = StructuredLLM.fromClient[IO](mockClient)

    val prompt: Prompt = Prompt.simple(
      "You are a helpful assistant",
      "Extract resume data"
    )

    for
      // Get streaming result
      (tokenStream: Stream[IO, String], resultF: IO[Resume]) <- structured.streamWithResult[Resume](prompt)

      // Collect tokens from stream
      tokens <- tokenStream.compile.toList

      // Get final parsed result
      result <- resultF

      // Verify tokens were emitted
      _ = assertEquals(tokens.size, 9, "Should emit 9 chunks")
      _ = assertEquals(tokens.mkString, fullJson, "Concatenated tokens should equal full JSON")

      // Verify final result was parsed correctly
      _ = assertEquals(result.name, "Jane Doe")
      _ = assertEquals(result.skills.toList, List("Scala", "FP"))
      _ = assertEquals(result.seniority, SeniorityLevel.SENIOR)
    yield ()
  }

  test("streamWithResult handles SAP error recovery") {
    // JSON with trailing comma (SAP should fix this)
    val malformedJson: String = """{"name": "Bob Smith", "skills": ["Java"], "seniority": "JUNIOR",}"""

    val mockClient: LLMClient = new LLMClient:
      override def complete(
        conversation: Conversation,
        options: CompletionOptions
      ): Result[Completion] =
        val completion: Completion = Completion(
          id = "mock-id",
          created = 0L,
          content = malformedJson,
          model = "mock-model",
          message = AssistantMessage(Some(malformedJson)),
          toolCalls = List.empty,
          usage = None,
          thinking = None
        )
        Right(completion)

      override def streamComplete(
        conversation: Conversation,
        options: CompletionOptions,
        onChunk: StreamedChunk => Unit
      ): Result[Completion] =
        // Emit as single chunk
        onChunk(StreamedChunk(
          id = "mock-chunk-id",
          content = Some(malformedJson),
          toolCall = None,
          finishReason = Some("stop"),
          thinkingDelta = None
        ))
        complete(conversation, options)

      override def getContextWindow(): Int = 8192
      override def getReserveCompletion(): Int = 512

    val structured: StructuredLLM[IO] = StructuredLLM.fromClient[IO](mockClient)

    val prompt: Prompt = Prompt.simple(
      "You are a helpful assistant",
      "Extract resume data"
    )

    for
      // Get streaming result
      (tokenStream: Stream[IO, String], resultF: IO[Resume]) <- structured.streamWithResult[Resume](prompt)

      // Consume stream (not checking tokens, just final result)
      _ <- tokenStream.compile.drain

      // Get final parsed result - SAP should fix the trailing comma
      result <- resultF

      // Verify result was parsed correctly despite malformed JSON
      _ = assertEquals(result.name, "Bob Smith")
      _ = assertEquals(result.skills.toList, List("Java"))
      _ = assertEquals(result.seniority, SeniorityLevel.JUNIOR)
    yield ()
  }

  test("streamWithResultRaw does not inject schema") {
    val jsonResponse: String = """{"name": "Alice Green", "skills": ["Python"], "seniority": "MID"}"""

    val mockClient: LLMClient = new LLMClient:
      override def complete(
        conversation: Conversation,
        options: CompletionOptions
      ): Result[Completion] =
        val completion: Completion = Completion(
          id = "mock-id",
          created = 0L,
          content = jsonResponse,
          model = "mock-model",
          message = AssistantMessage(Some(jsonResponse)),
          toolCalls = List.empty,
          usage = None,
          thinking = None
        )
        Right(completion)

      override def streamComplete(
        conversation: Conversation,
        options: CompletionOptions,
        onChunk: StreamedChunk => Unit
      ): Result[Completion] =
        onChunk(StreamedChunk(
          id = "mock-chunk-id",
          content = Some(jsonResponse),
          toolCall = None,
          finishReason = Some("stop"),
          thinkingDelta = None
        ))
        complete(conversation, options)

      override def getContextWindow(): Int = 8192
      override def getReserveCompletion(): Int = 512

    val structured: StructuredLLM[IO] = StructuredLLM.fromClient[IO](mockClient)

    // Prompt already has schema in it
    val promptWithSchema: Prompt = Prompt(
      SystemMessage("You are a helpful assistant"),
      UserMessage("Respond with JSON matching Resume schema")
    )

    for
      // Use raw variant - should not inject schema again
      (tokenStream: Stream[IO, String], resultF: IO[Resume]) <- structured.streamWithResultRaw[Resume](promptWithSchema)

      // Consume stream
      _ <- tokenStream.compile.drain

      // Get final result
      result <- resultF

      // Verify parsing worked
      _ = assertEquals(result.name, "Alice Green")
      _ = assertEquals(result.skills.toList, List("Python"))
      _ = assertEquals(result.seniority, SeniorityLevel.MID)
    yield ()
  }
